# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField()),
                ('title', models.CharField(max_length=25)),
                ('portada', models.FileField(upload_to='')),
                ('author', models.CharField(max_length=30)),
                ('editorial', models.CharField(max_length=25)),
                ('pais', models.CharField(max_length=50)),
                ('anio', models.IntegerField()),
            ],
        ),
    ]
